name: Run Tests and Upload to Codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test with code coverage and junit
      run: >
        dotnet test --no-build --configuration Release
        --collect:"XPlat Code Coverage"
        --logger:"junit;LogFilePath=TestResults/test-results.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
        --results-directory ./TestResults

    - name: Run tests and generate TRX
      run: >
          dotnet test --no-build --configuration Release
          --collect:"XPlat Code Coverage"
          --logger "trx;LogFileName=test-results.trx"
          --results-directory ./TestResults


    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./TestResults/**/coverage.cobertura.xml
        flags: unittests
        name: codecov-coverage
        verbose: true

    - name: Upload test results to Codecov
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./TestResults/test-results.xml
