name: Run Tests and Upload to Codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests and generate coverage and trx
      run: >
        dotnet test --no-build --configuration Release
        --collect:"XPlat Code Coverage"
        --logger "trx;LogFileName=test-results.trx"
        --results-directory ./TestResults
        -p:GenerateFullPaths=true

    - name: Install trx2junit
      run: dotnet tool install --global trx2junit

    - name: Convert TRX to JUnit
      run: trx2junit ./TestResults/test-results.trx

    - name: Show generated test result
      run: ls -l ./TestResults

    - name: Debug - Show contents of TestResults
      run: ls -R ./TestResults


    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./TestResults/**/coverage.cobertura.xml
        flags: unittests
        name: codecov-coverage
        verbose: true

    - name: Upload test results to Codecov
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./TestResults/TEST-*.xml
